name: CI

on:
  pull_request:
    branches: [ "**" ]
  push:
    tags:
      - "v*"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Nix
        uses: cachix/install-nix-action@v27

      - name: Show Nix version
        run: nix --version

      - name: Make ABI and test
        run: |
          make abi
          make test

      - name: Build WASM package
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          make wasm
          cd js
          tar czf ../rain-float-js.tar.gz *

      - name: Upload JS artifact
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v4
        with:
          name: rain-float-wasm
          path: rain-float-wasm.tar.gz

      - name: Create or update draft GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: rain-float-js.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}